import { ProposalCardType, SingleChoiceEnum, VotingEnum } from "@/types/proposal";
import dayjs from "dayjs";

export const defaultSingleChoice = [SingleChoiceEnum.YES, SingleChoiceEnum.NO, SingleChoiceEnum.ABSTAIN];

export const mockProposals: ProposalCardType[] = [
  {
    id: "1",
    maxSelection: 1,
    proposer: "0x1234567890abcdef1234567890abcdef12345678",
    createdAt: new Date("2025-01-01T00:00:00"),
    headerImage: "/images/proposal_example.png",
    isVoted: true,
    status: "voting",
    description:
      "Galactica is the first of three stages of the VeChain Renaissance - a revolutionary technical roadmap and generational leap for the protocol. Galactica begins a process that will ultimately upgrade VeChainThor’s tokenomic, governance and technical capabilities, placing community at the core and tying rewards to network contributions. (To review technical changes, including the massive upgrades to VeChain’s tokenomic model, see our recent release here)",
    title: "All-Stakeholder Voting Proposal: Galactica Launch & Governance Upgrade",
    startDate: dayjs().subtract(1, "day").toDate(),
    endDate: dayjs().add(1, "day").toDate(),
    question: "Do you agree with the voting proposal Galactica launch & Governance upgrade?",
    votingType: VotingEnum.SINGLE_CHOICE,
    votingOptions: defaultSingleChoice,
  },
  {
    id: "2",
    maxSelection: 1,
    proposer: "0x1234567890abcdef1234567890abcdef12345678",
    createdAt: new Date("2025-01-01T00:00:00"),
    headerImage: "/images/proposal_example.png",
    isVoted: false,
    status: "voting",
    description:
      "Galactica is the first of three stages of the VeChain Renaissance - a revolutionary technical roadmap and generational leap for the protocol. Galactica begins a process that will ultimately upgrade VeChainThor’s tokenomic, governance and technical capabilities, placing community at the core and tying rewards to network contributions. (To review technical changes, including the massive upgrades to VeChain’s tokenomic model, see our recent release here)",
    title: "Upcoming Proposal: Galactica Launch & Governance Upgrade",
    startDate: dayjs().subtract(2, "day").toDate(),
    endDate: dayjs().add(1, "day").toDate(),
    question: "Do you agree with the voting proposal Galactica launch & Governance upgrade?",
    votingType: VotingEnum.SINGLE_OPTION,
    votingOptions: ["option1", "option2", "option3"],
  },
  {
    id: "3",
    maxSelection: 3,
    proposer: "0x1234567890abcdef1234567890abcdef12345678",
    createdAt: new Date("2025-01-01T00:00:00"),
    headerImage: "/images/proposal_example.png",
    isVoted: true,
    status: "voting",
    description:
      "Galactica is the first of three stages of the VeChain Renaissance - a revolutionary technical roadmap and generational leap for the protocol. Galactica begins a process that will ultimately upgrade VeChainThor’s tokenomic, governance and technical capabilities, placing community at the core and tying rewards to network contributions. (To review technical changes, including the massive upgrades to VeChain’s tokenomic model, see our recent release here)",
    title: "Approved Proposal: Galactica Launch & Governance Upgrade",
    startDate: dayjs().subtract(3, "day").toDate(),
    endDate: dayjs().add(1, "day").toDate(),
    question: "Do you agree with the voting proposal Galactica launch & Governance upgrade?",
    votingType: VotingEnum.MULTIPLE_OPTIONS,
    votingOptions: ["option1", "option2", "option3"],
  },
  {
    id: "4",
    maxSelection: 1,
    proposer: "0x1234567890abcdef1234567890abcdef12345678",
    createdAt: new Date("2025-01-01T00:00:00"),
    headerImage: "/images/proposal_example.png",
    isVoted: true,
    status: "executed",
    description:
      "Galactica is the first of three stages of the VeChain Renaissance - a revolutionary technical roadmap and generational leap for the protocol. Galactica begins a process that will ultimately upgrade VeChainThor’s tokenomic, governance and technical capabilities, placing community at the core and tying rewards to network contributions. (To review technical changes, including the massive upgrades to VeChain’s tokenomic model, see our recent release here)",
    title: "Executed Proposal: Galactica Launch & Governance Upgrade",
    startDate: dayjs().subtract(4, "day").toDate(),
    endDate: dayjs().subtract(3, "day").toDate(),
    question: "Do you agree with the voting proposal Galactica launch & Governance upgrade?",
    votingType: VotingEnum.SINGLE_CHOICE,
    votingOptions: defaultSingleChoice,
  },
  {
    id: "5",
    maxSelection: 1,
    proposer: "0x1234567890abcdef1234567890abcdef12345678",
    createdAt: new Date("2025-01-01T00:00:00"),
    headerImage: "/images/proposal_example.png",
    isVoted: true,
    status: "rejected",
    description:
      "Galactica is the first of three stages of the VeChain Renaissance - a revolutionary technical roadmap and generational leap for the protocol. Galactica begins a process that will ultimately upgrade VeChainThor’s tokenomic, governance and technical capabilities, placing community at the core and tying rewards to network contributions. (To review technical changes, including the massive upgrades to VeChain’s tokenomic model, see our recent release here)",
    title: "Rejected Proposal: Galactica Launch & Governance Upgrade",
    startDate: dayjs().subtract(4, "day").toDate(),
    endDate: dayjs().subtract(3, "day").toDate(),
    question: "Do you agree with the voting proposal Galactica launch & Governance upgrade?",
    votingType: VotingEnum.SINGLE_CHOICE,
    votingOptions: defaultSingleChoice,
  },
  {
    id: "6",
    maxSelection: 1,
    proposer: "0x1234567890abcdef1234567890abcdef12345678",
    createdAt: new Date("2025-01-01T00:00:00"),
    headerImage: "/images/proposal_example.png",
    isVoted: false,
    status: "canceled",
    description:
      "Galactica is the first of three stages of the VeChain Renaissance - a revolutionary technical roadmap and generational leap for the protocol. Galactica begins a process that will ultimately upgrade VeChainThor’s tokenomic, governance and technical capabilities, placing community at the core and tying rewards to network contributions.(To review technical changes, including the massive upgrades to VeChain’s tokenomic model, see our recent release here)",
    title: "Canceled Proposal: Galactica Launch",
    endDate: dayjs().subtract(3, "day").toDate(),
    startDate: dayjs().subtract(3, "day").toDate(),
    question: "Do you agree with the voting proposal Galactica launch & Governance upgrade?",
    votingType: VotingEnum.SINGLE_CHOICE,
    votingOptions: defaultSingleChoice,
  },
];
