project: vevote
project_alias: ve
tag: latest
vercel_team_id: team_gWCnY5uRnzsZIb5SvnCXAIjH
domain_name: vevote.vechain.org
public_zone_name: vevote.vechain.org
origin_id: vevote.vechain.org
environment: prod
region: eu-west-1
domain_name: vote.vechain.org

all_environments:
  mnemonic: denial kitchen pet squirrel other broom bar gas better priority spoil cross
  TESTNET_STAGING_MNEMONIC: belt enemy list bless taxi produce inner whale urge width sauce release
  public_ipfs_pinning_service: https://api.gateway-proxy.vechain.org/api/v1/pinning/pinFileToIPFS
  vechain_url_devnet: https://galactica.green.dev.node.vechain.org/
