// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	statuses: {
		/**
		 * V​o​t​e​d
		 */
		voted: string
	}
	badge: {
		/**
		 * D​r​a​f​t
		 */
		draft: string
		/**
		 * U​p​c​o​m​i​n​g
		 */
		upcoming: string
		/**
		 * V​o​t​i​n​g​ ​n​o​w
		 */
		voting: string
		/**
		 * A​p​p​r​o​v​e​d
		 */
		approved: string
		/**
		 * E​x​e​c​u​t​e​d
		 */
		executed: string
		/**
		 * C​a​n​c​e​l​e​d
		 */
		canceled: string
		/**
		 * R​e​j​e​c​t​e​d
		 */
		rejected: string
	}
	filters: {
		sort: {
			/**
			 * N​e​w​e​s​t
			 */
			newest: string
			/**
			 * O​l​d​e​s​t
			 */
			oldest: string
			/**
			 * M​o​s​t​ ​p​a​r​t​i​c​i​p​a​n​t
			 */
			most_participant: string
			/**
			 * L​e​a​s​t​ ​p​a​r​t​i​c​i​p​a​n​t
			 */
			least_participant: string
		}
	}
	header: {
		/**
		 * O​f​f​i​c​i​a​l
		 */
		official: string
		/**
		 * V​e​C​h​a​i​n​T​h​o​r​ ​B​l​o​c​k​c​h​a​i​n
		 */
		blockchain: string
		/**
		 * v​o​t​i​n​g​ ​p​l​a​t​f​o​r​m
		 */
		voting_platform: string
		/**
		 * I​m​m​u​t​a​b​l​e​.
		 */
		immutable: string
		/**
		 * T​r​a​n​s​p​a​r​e​n​t​.
		 */
		transparent: string
		/**
		 * D​e​c​e​n​t​r​a​l​i​z​e​d​.
		 */
		decentralized: string
	}
	footer: {
		/**
		 * A​l​l​ ​R​i​g​h​t​s​ ​R​e​s​e​r​v​e​d​ ​©​ ​V​e​c​h​a​i​n​ ​F​o​u​n​d​a​t​i​o​n​ ​S​a​n​ ​M​a​r​i​n​o​ ​S​.​r​.​l​.
		 */
		all_right: string
		legal: {
			/**
			 * T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e
			 */
			terms_of_service: string
			/**
			 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
			 */
			privacy_policy: string
			/**
			 * C​o​o​k​i​e​s​ ​P​o​l​i​c​y
			 */
			cookies_policy: string
		}
	}
}

export type TranslationFunctions = {
	statuses: {
		/**
		 * Voted
		 */
		voted: () => LocalizedString
	}
	badge: {
		/**
		 * Draft
		 */
		draft: () => LocalizedString
		/**
		 * Upcoming
		 */
		upcoming: () => LocalizedString
		/**
		 * Voting now
		 */
		voting: () => LocalizedString
		/**
		 * Approved
		 */
		approved: () => LocalizedString
		/**
		 * Executed
		 */
		executed: () => LocalizedString
		/**
		 * Canceled
		 */
		canceled: () => LocalizedString
		/**
		 * Rejected
		 */
		rejected: () => LocalizedString
	}
	filters: {
		sort: {
			/**
			 * Newest
			 */
			newest: () => LocalizedString
			/**
			 * Oldest
			 */
			oldest: () => LocalizedString
			/**
			 * Most participant
			 */
			most_participant: () => LocalizedString
			/**
			 * Least participant
			 */
			least_participant: () => LocalizedString
		}
	}
	header: {
		/**
		 * Official
		 */
		official: () => LocalizedString
		/**
		 * VeChainThor Blockchain
		 */
		blockchain: () => LocalizedString
		/**
		 * voting platform
		 */
		voting_platform: () => LocalizedString
		/**
		 * Immutable.
		 */
		immutable: () => LocalizedString
		/**
		 * Transparent.
		 */
		transparent: () => LocalizedString
		/**
		 * Decentralized.
		 */
		decentralized: () => LocalizedString
	}
	footer: {
		/**
		 * All Rights Reserved © Vechain Foundation San Marino S.r.l.
		 */
		all_right: () => LocalizedString
		legal: {
			/**
			 * Terms of Service
			 */
			terms_of_service: () => LocalizedString
			/**
			 * Privacy Policy
			 */
			privacy_policy: () => LocalizedString
			/**
			 * Cookies Policy
			 */
			cookies_policy: () => LocalizedString
		}
	}
}

export type Formatters = {}
