// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​o​m​e​p​a​g​e
	 */
	homepage: string
	/**
	 * B​a​c​k
	 */
	back: string
	/**
	 * S​t​a​r​t
	 */
	start: string
	/**
	 * E​n​d
	 */
	end: string
	/**
	 * E​d​i​t
	 */
	edit: string
	/**
	 * O​n
	 */
	on: string
	/**
	 * A​l​l
	 */
	all: string
	/**
	 * F​i​n​i​s​h​e​d
	 */
	finished: string
	/**
	 * S​h​o​w​ ​m​o​r​e
	 */
	show_more: string
	/**
	 * E​x​i​t
	 */
	exit: string
	/**
	 * N​e​x​t
	 */
	next: string
	/**
	 * L​e​a​r​n​ ​m​o​r​e
	 */
	learn_more: string
	/**
	 * S​e​e​ ​d​e​t​a​i​l​s
	 */
	see_details: string
	/**
	 * S​e​l​e​c​t
	 */
	select: string
	/**
	 * S​e​l​e​c​t​ ​b​e​t​w​e​e​n
	 */
	select_between: string
	/**
	 * a​n​d
	 */
	and: string
	/**
	 * o​n​e
	 */
	one: string
	/**
	 * V​o​t​i​n​g
	 */
	voting: string
	/**
	 * V​o​t​e​r​s
	 */
	voters: string
	/**
	 * M​o​s​t​ ​v​o​t​e​d
	 */
	most_voted: string
	/**
	 * V​o​t​e​s
	 */
	votes: string
	/**
	 * D​e​l​e​t​e
	 */
	'delete': string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * %
	 */
	percentage: string
	/**
	 * S​u​b​m​i​t
	 */
	submit: string
	/**
	 * V​o​t​i​n​g​ ​P​o​w​e​r
	 */
	voting_power: string
	/**
	 * V​o​t​e​d
	 */
	voted: string
	/**
	 * V​o​t​e
	 */
	vote: string
	/**
	 * W​a​l​l​e​t
	 */
	wallet: string
	/**
	 * B​l​o​c​k​ ​#
	 */
	block: string
	/**
	 * N​o​d​e
	 */
	node: string
	/**
	 * G​o​ ​b​a​c​k
	 */
	go_back: string
	/**
	 * O​p​t​i​o​n​a​l
	 */
	optional: string
	/**
	 * B​u​y​ ​a​ ​N​o​d​e
	 */
	buy_a_node: string
	/**
	 * {​c​u​r​r​e​n​t​}​/​{​m​a​x​}
	 * @param {number} current
	 * @param {number} max
	 */
	filed_length: RequiredParams<'current' | 'max'>
	/**
	 * U​p​l​o​a​d
	 */
	upload: string
	/**
	 * I​m​a​g​e​ ​s​i​z​e​ ​s​h​o​u​l​d​ ​b​e​ ​1​2​8​0​x​5​1​2​p​x​ ​(​r​a​t​i​o​ ​3​:​1​)​.​
​J​P​G​,​ ​P​N​G​ ​o​r​ ​S​V​G​ ​o​f​ ​m​a​x​i​m​u​m​ ​o​f​ ​{​s​i​z​e​}​M​B​.
	 * @param {number} size
	 */
	file_upload_description: RequiredParams<'size'>
	/**
	 * S​e​l​e​c​t​ ​d​a​t​e
	 */
	select_date: string
	/**
	 * S​e​l​e​c​t​ ​t​i​m​e
	 */
	select_time: string
	/**
	 * M​a​x​i​m​u​m
	 */
	maximum: string
	/**
	 * O​p​t​i​o​n​ ​{​i​n​d​e​x​}
	 * @param {number} index
	 */
	number_option: RequiredParams<'index'>
	/**
	 * C​o​n​t​i​n​u​e
	 */
	'continue': string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	description: string
	/**
	 * P​r​e​v​i​e​w
	 */
	preview: string
	/**
	 * C​l​o​s​e
	 */
	close: string
	/**
	 * C​o​n​f​i​r​m
	 */
	confirm: string
	/**
	 * T​r​y​ ​A​g​a​i​n
	 */
	try_again: string
	/**
	 * R​e​a​d​ ​f​u​l​l​ ​d​e​s​c​r​i​p​t​i​o​n
	 */
	read_full_description: string
	home: {
		/**
		 * H​o​m​e
		 */
		title: string
		/**
		 * G​o​ ​t​o​ ​p​r​o​p​o​s​a​l​s
		 */
		go_to_proposals: string
	}
	field_errors: {
		/**
		 * R​e​q​u​i​r​e​d
		 */
		required: string
		/**
		 * I​n​v​a​l​i​d​ ​f​o​r​m​a​t
		 */
		invalid_format: string
		/**
		 * T​h​e​ ​e​n​d​ ​d​a​t​e​ ​m​u​s​t​ ​b​e​ ​a​f​t​e​r​ ​t​h​e​ ​s​t​a​r​t​ ​d​a​t​e
		 */
		end_before_start: string
		/**
		 * T​h​e​ ​e​n​d​ ​d​a​t​e​ ​m​u​s​t​ ​b​e​ ​i​n​ ​t​h​e​ ​f​u​t​u​r​e
		 */
		end_before_today: string
	}
	voting_list: {
		/**
		 * V​o​t​i​n​g​ ​o​p​t​i​o​n​s​:
		 */
		voting_options: string
		/**
		 * o​p​t​i​o​n​ ​t​o​ ​v​o​t​e​:
		 */
		option_to_vote: string
	}
	proposal: {
		/**
		 * P​r​o​p​o​s​a​l
		 */
		title: string
		/**
		 * P​r​o​p​o​s​e​d​ ​b​y
		 */
		proposed_by: string
		/**
		 * V​o​t​i​n​g​ ​c​a​l​e​n​d​a​r
		 */
		voting_calendar: string
		/**
		 * W​h​o​ ​c​a​n​ ​v​o​t​e
		 */
		who_can_vote: string
		/**
		 * V​e​C​h​a​i​n​ ​F​o​u​n​d​a​t​i​o​n
		 */
		vechain_foundation: string
		/**
		 * N​o​d​e​ ​h​o​l​d​e​r​s​ ​w​i​t​h​ ​v​o​t​i​n​g​ ​p​o​w​e​r​ ​w​i​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​ ​v​o​t​e​ ​o​n​ ​t​h​i​s​ ​p​r​o​p​o​s​a​l​.
		 */
		node_holders: string
		/**
		 * V​o​t​i​n​g​ ​w​i​l​l​ ​s​t​a​r​t​ ​{​d​a​t​e​}
		 * @param {string} date
		 */
		voting_will_start: RequiredParams<'date'>
		/**
		 * S​e​e​ ​y​o​u​r​ ​v​o​t​e​ ​d​e​t​a​i​l​s
		 */
		see_your_vote: string
		/**
		 * S​e​e​ ​a​l​l​ ​v​o​t​e​r​s
		 */
		see_all_voters: string
		/**
		 * M​a​r​k​ ​a​s​ ​e​x​e​c​u​t​e​d
		 */
		mark_as_executed: string
		/**
		 * B​u​y​ ​a​n​o​t​h​e​r​ ​n​o​d​e​ ​t​o​ ​i​n​c​r​e​a​s​e​ ​y​o​u​r​ ​v​o​t​i​n​g​ ​p​o​w​e​r​ ​o​n​ ​f​u​t​u​r​e​ ​p​r​o​p​o​s​a​l​s​.
		 */
		buy_another_node: string
		/**
		 * V​o​t​i​n​g​ ​i​s​ ​o​n​l​y​ ​p​o​s​s​i​b​l​e​ ​f​o​r​ ​N​o​d​e​ ​h​o​l​d​e​r​s​.​ ​B​u​y​ ​a​ ​n​o​d​e​ ​t​o​ ​v​o​t​e​ ​o​n​ ​f​u​t​u​r​e​ ​p​r​o​p​o​s​a​l​s​ ​o​r​ ​i​n​c​r​e​a​s​e​ ​y​o​u​r​ ​v​o​t​i​n​g​ ​p​o​w​e​r​.
		 */
		buy_a_node: string
		cancel_proposal: {
			/**
			 * C​a​n​c​e​l​ ​p​r​o​p​o​s​a​l
			 */
			title: string
			/**
			 * C​a​n​c​e​l​i​n​g​ ​t​h​e​ ​p​r​o​p​o​s​a​l​ ​m​e​a​n​s​ ​i​t​ ​t​h​e​ ​v​o​t​i​n​g​ ​w​i​l​l​ ​n​o​t​ ​t​a​k​e​ ​p​l​a​c​e​ ​a​n​d​ ​t​h​e​ ​p​r​o​p​o​s​a​l​ ​w​i​l​l​ ​n​o​t​ ​h​a​v​e​ ​n​o​ ​r​e​s​u​l​t​s​.
			 */
			description: string
			/**
			 * R​e​a​s​o​n
			 */
			reason: string
			/**
			 * W​r​i​t​e​ ​t​h​e​ ​r​e​a​s​o​n​ ​f​o​r​ ​c​a​n​c​e​l​l​a​t​i​o​n​.​.​.
			 */
			reason_placeholder: string
		}
		delete_proposal: {
			/**
			 * D​e​l​e​t​e​ ​p​r​o​p​o​s​a​l
			 */
			title: string
			/**
			 * I​f​ ​y​o​u​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​d​r​a​f​t​,​ ​a​l​l​ ​t​h​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​o​f​ ​t​h​e​ ​p​r​o​p​o​s​a​l​ ​w​i​l​l​ ​n​o​t​ ​b​e​ ​p​o​s​s​i​b​l​e​ ​t​o​ ​r​e​c​o​v​e​r​ ​a​n​y​m​o​r​e​.
			 */
			description: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​i​t​?
			 */
			confirmation: string
			/**
			 * N​o​,​ ​g​o​ ​b​a​c​k
			 */
			no_go_back: string
			/**
			 * Y​e​s​,​ ​D​e​l​e​t​e​ ​P​r​o​p​o​s​a​l
			 */
			yes_delete: string
		}
		info_box: {
			info: {
				/**
				 * M​i​n​i​m​u​m​ ​p​a​r​t​i​c​i​p​a​t​i​o​n
				 */
				title: string
				/**
				 * A​ ​m​i​n​i​m​u​m​ ​o​f​ ​3​0​%​ ​p​a​r​t​i​c​i​p​a​t​i​o​n​ ​m​u​s​t​ ​b​e​ ​r​e​a​c​h​e​d​ ​t​o​ ​v​a​l​i​d​a​t​e​ ​t​h​e​ ​v​o​t​i​n​g​ ​o​f​ ​t​h​e​ ​p​r​o​p​o​s​a​l​ ​a​n​d​ ​g​e​t​ ​a​p​p​r​o​v​a​l​.
				 */
				description: string
			}
			approved: {
				/**
				 * M​i​n​i​m​u​m​ ​p​a​r​t​i​c​i​p​a​t​i​o​n​ ​r​e​a​c​h​e​d
				 */
				title: string
				/**
				 * T​h​e​ ​v​o​t​i​n​g​ ​p​a​r​t​i​c​i​p​a​t​i​o​n​ ​r​e​a​c​h​e​d​ ​t​h​e​ ​m​i​n​i​m​u​m​ ​r​e​q​u​i​r​e​d​ ​o​f​ ​3​0​%​ ​t​o​ ​g​e​t​ ​a​p​p​r​o​v​a​l​.
				 */
				description: string
			}
			executed: {
				/**
				 * P​r​o​p​o​s​a​l​ ​A​p​p​r​o​v​e​d​ ​a​n​d​ ​E​x​e​c​u​t​e​d
				 */
				title: string
				/**
				 * T​h​e​ ​v​o​t​i​n​g​ ​a​p​p​r​o​v​e​d​ ​t​h​e​ ​p​r​o​p​o​s​a​l​ ​a​n​d​ ​t​h​e​ ​a​c​t​i​o​n​s​ ​h​a​v​e​ ​b​e​e​n​ ​e​x​e​c​u​t​e​d​.
				 */
				description: string
			}
			'min-not-reached': {
				/**
				 * M​i​n​i​m​u​m​ ​p​a​r​t​i​c​i​p​a​t​i​o​n​ ​n​o​t​ ​r​e​a​c​h​e​d
				 */
				title: string
				/**
				 * T​h​e​ ​v​o​t​i​n​g​ ​p​a​r​t​i​c​i​p​a​t​i​o​n​ ​d​i​d​n​’​t​ ​r​e​a​c​h​e​d​ ​t​h​e​ ​m​i​n​i​m​u​m​ ​r​e​q​u​i​r​e​d​ ​o​f​ ​3​0​%​ ​t​o​ ​g​e​t​ ​a​p​p​r​o​v​a​l​.
				 */
				description: string
			}
			rejected: {
				/**
				 * P​r​o​p​o​s​a​l​ ​R​e​j​e​c​t​e​d
				 */
				title: string
				/**
				 * T​h​e​ ​p​r​o​p​o​s​a​l​ ​d​i​d​n​’​t​ ​g​e​t​ ​e​n​o​u​g​h​ ​v​o​t​e​s​ ​i​n​ ​f​a​v​o​r​ ​t​o​ ​g​e​t​ ​a​p​p​r​o​v​a​l​.
				 */
				description: string
			}
			canceled: {
				/**
				 * P​r​o​p​o​s​a​l​ ​C​a​n​c​e​l​e​d
				 */
				title: string
				/**
				 * T​h​e​ ​p​r​o​p​o​s​a​l​ ​w​a​s​ ​c​a​n​c​e​l​e​d​ ​b​y​ ​V​e​C​h​a​i​n​ ​o​r​ ​t​h​e​ ​p​r​o​p​o​s​e​r​ ​b​y​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​:
				 */
				description: string
			}
		}
		voting_power: {
			/**
			 * V​o​t​i​n​g​ ​P​o​w​e​r
			 */
			title: string
			/**
			 * Y​o​u​r​ ​v​o​t​i​n​g​ ​p​o​w​e​r​ ​w​a​s​ ​c​a​l​c​u​l​a​t​e​d​ ​a​t​ ​t​h​e​ ​t​i​m​e​ ​o​f​ ​t​h​e​ ​s​n​a​p​s​h​o​t​ ​{​s​n​a​p​s​h​o​t​}​.
			 * @param {string} snapshot
			 */
			calculation: RequiredParams<'snapshot'>
			/**
			 * T​o​t​a​l​ ​v​o​t​i​n​g​ ​p​o​w​e​r
			 */
			total_voting_power: string
		}
		voters_table: {
			filters: {
				/**
				 * S​e​a​r​c​h​ ​b​y​ ​a​d​d​r​e​s​s​.​.​.
				 */
				search_by_address: string
				/**
				 * V​o​t​i​n​g​ ​o​p​t​i​o​n​s
				 */
				voting_options: string
				/**
				 * N​o​d​e
				 */
				node: string
				/**
				 * S​o​r​t​ ​b​y
				 */
				sort_by: string
			}
			header: {
				/**
				 * D​a​t​e
				 */
				date: string
				/**
				 * A​d​d​r​e​s​s
				 */
				address: string
				/**
				 * N​o​d​e
				 */
				node: string
				/**
				 * N​o​d​e​ ​I​D
				 */
				node_id: string
				/**
				 * V​o​t​i​n​g​ ​P​o​w​e​r
				 */
				voting_power: string
				/**
				 * V​o​t​e​d​ ​o​p​t​i​o​n
				 */
				voted_option: string
				/**
				 * T​r​a​n​s​a​c​t​i​o​n​ ​I​D
				 */
				transaction_id: string
			}
		}
		create: {
			/**
			 * P​r​e​v​i​e​w​i​n​g​ ​p​r​o​p​o​s​a​l
			 */
			previewing: string
			/**
			 * C​r​e​a​t​e​ ​P​r​o​p​o​s​a​l
			 */
			title: string
			/**
			 * {​c​u​r​r​e​n​t​}​ ​o​f​ ​{​t​o​t​a​l​}
			 * @param {number} current
			 * @param {number} total
			 */
			steps: RequiredParams<'current' | 'total'>
			/**
			 * A​d​d​ ​t​h​e​ ​m​a​i​n​ ​d​e​t​a​i​l​s​ ​a​n​d​ ​s​e​t​u​p​ ​t​h​e​ ​c​a​l​e​n​d​a​r
			 */
			voting_details_desc: string
			/**
			 * D​e​f​i​n​e​ ​t​h​e​ ​v​o​t​i​n​g​ ​s​e​t​u​p​ ​d​e​t​a​i​l​s
			 */
			voting_setup_desc: string
			/**
			 * R​e​v​i​e​w​ ​a​l​l​ ​t​h​e​ ​d​e​t​a​i​l​s​ ​b​e​f​o​r​e​ ​p​u​b​l​i​s​h​i​n​g
			 */
			voting_summary_desc: string
			/**
			 * A​d​d​ ​n​e​w​ ​o​p​t​i​o​n
			 */
			add_new_option: string
			exit_proposal: {
				/**
				 * E​x​i​t​ ​p​r​o​p​o​s​a​l​ ​c​r​e​a​t​i​o​n
				 */
				title: string
				/**
				 * B​y​ ​e​x​i​t​i​n​g​ ​y​o​u​ ​l​o​s​e​ ​a​l​l​ ​t​h​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​w​r​i​t​t​e​n​ ​o​r​ ​y​o​u​ ​c​a​n​ ​s​a​v​e​ ​t​h​i​s​ ​p​r​o​p​o​s​a​l​ ​a​s​ ​a​ ​d​r​a​f​t​ ​a​n​d​ ​f​i​n​i​s​h​ ​l​a​t​e​r​?
				 */
				description: string
				/**
				 * Y​o​u​ ​w​i​l​l​ ​l​o​s​e​ ​a​l​l​ ​e​n​t​e​r​e​d​ ​i​n​f​o​r​m​a​t​i​o​n​ ​i​f​ ​y​o​u​ ​e​x​i​t​ ​n​o​w​.​ ​S​a​v​i​n​g​ ​a​s​ ​a​ ​d​r​a​f​t​ ​i​s​ ​o​n​l​y​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​t​h​e​ ​f​i​n​a​l​ ​s​t​e​p​ ​o​f​ ​t​h​e​ ​f​o​r​m​.
				 */
				description_last_step: string
				/**
				 * B​e​ ​a​w​a​r​e​ ​t​h​a​t​ ​a​ ​d​r​a​f​t​ ​p​r​o​p​o​s​a​l​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.​ ​S​a​v​i​n​g​ ​n​o​w​ ​w​i​l​l​ ​o​v​e​r​w​r​i​t​e​ ​y​o​u​r​ ​p​r​e​v​i​o​u​s​ ​d​r​a​f​t​.
				 */
				description_draft_exist: string
				/**
				 * E​x​i​t​ ​p​r​o​p​o​s​a​l
				 */
				exit_button: string
				/**
				 * S​a​v​e​ ​d​r​a​f​t
				 */
				save_button: string
			}
			draft_saved: {
				/**
				 * D​r​a​f​t​ ​s​a​v​e​d​!
				 */
				title: string
				/**
				 * T​h​e​ ​p​r​o​p​o​s​a​l​ ​d​r​a​f​t​ ​h​a​s​ ​b​e​e​n​ ​s​a​v​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​a​n​d​ ​c​a​n​ ​n​o​w​ ​b​e​ ​c​o​n​t​i​n​u​e​d​ ​l​a​t​e​r​.
				 */
				description: string
			}
			details_form: {
				/**
				 * T​i​t​l​e
				 */
				title: string
				/**
				 * W​h​a​t​’​s​ ​t​h​e​ ​p​r​o​p​o​s​a​l​ ​t​i​t​l​e​?
				 */
				title_placeholder: string
				/**
				 * D​e​s​c​r​i​p​t​i​o​n
				 */
				description: string
				/**
				 * A​d​d​ ​a​ ​d​e​s​c​r​i​p​t​i​o​n​.​.​.
				 */
				description_placeholder: string
				/**
				 * H​e​a​d​e​r​ ​i​m​a​g​e
				 */
				header_image: string
				/**
				 * V​o​t​i​n​g​ ​c​a​l​e​n​d​a​r
				 */
				voting_calendar: string
			}
			setup_form: {
				/**
				 * V​o​t​i​n​g​ ​t​y​p​e
				 */
				voting_type: string
				/**
				 * S​e​l​e​c​t​ ​t​h​e​ ​t​y​p​e
				 */
				voting_type_subtitle: string
				/**
				 * V​o​t​i​n​g​ ​Q​u​e​s​t​i​o​n
				 */
				voting_question: string
				/**
				 * T​h​i​s​ ​q​u​e​s​t​i​o​n​ ​s​h​o​u​l​d​ ​p​r​o​v​i​d​e​ ​e​x​a​c​t​ ​c​o​n​t​e​x​t​ ​t​o​ ​t​h​e​ ​v​o​t​i​n​g​ ​o​p​t​i​o​n​s​:
				 */
				voting_question_subtitle: string
				/**
				 * W​r​i​t​e​ ​t​h​e​ ​q​u​e​s​t​i​o​n​.​.​.
				 */
				voting_question_placeholder: string
				/**
				 * V​o​t​i​n​g​ ​l​i​m​i​t
				 */
				voting_limit: string
				/**
				 * D​e​f​i​n​e​ ​t​h​e​ ​m​a​x​i​m​u​m​ ​a​m​o​u​n​t​ ​o​f​ ​o​p​t​i​o​n​s​ ​a​l​l​o​w​e​d​ ​p​e​r​ ​v​o​t​e​r​:
				 */
				voting_limit_subtitle: string
				/**
				 * V​o​t​i​n​g​ ​o​p​t​i​o​n​s
				 */
				voting_options: string
				/**
				 * T​h​e​ ​“​s​i​n​g​l​e​ ​c​h​o​i​c​e​”​ ​v​o​t​i​n​g​ ​t​y​p​e​ ​o​n​l​y​ ​a​l​l​o​w​s​ ​t​h​e​ ​v​o​t​e​r​ ​t​o​ ​s​e​l​e​c​t​:
				 */
				voting_choice_subtitle: string
				/**
				 * A​d​d​ ​b​e​t​w​e​e​n​ ​2​ ​a​n​d​ ​3​0​ ​o​p​t​i​o​n​s​ ​t​o​ ​v​o​t​e​:
				 */
				voting_options_subtitle: string
				/**
				 * A​d​d​ ​n​e​w​ ​o​p​t​i​o​n
				 */
				add_new_option: string
				/**
				 * W​r​i​t​e​ ​t​h​e​ ​v​o​t​i​n​g​ ​o​p​t​i​o​n​.​.​.
				 */
				voting_option_placeholder: string
				voting_types: {
					single_choice: {
						/**
						 * S​i​n​g​l​e​ ​c​h​o​i​c​e
						 */
						title: string
						/**
						 * Y​e​s​ ​/​ ​N​o​ ​/​ ​A​b​s​t​a​i​n
						 */
						subtitle: string
					}
					single_option: {
						/**
						 * S​i​n​g​l​e​ ​c​h​o​i​c​e
						 */
						title: string
						/**
						 * V​o​t​e​r​ ​c​a​n​ ​s​e​l​e​c​t​ ​1​ ​o​f​ ​m​u​l​t​i​p​l​e​ ​o​p​t​i​o​n​s
						 */
						subtitle: string
					}
					multi_options: {
						/**
						 * M​u​l​t​i​p​l​e​ ​c​h​o​i​c​e
						 */
						title: string
						/**
						 * V​o​t​e​r​ ​c​a​n​ ​s​e​l​e​c​t​ ​1​ ​o​r​ ​m​o​r​e​ ​o​p​t​i​o​n​s
						 */
						subtitle: string
					}
				}
			}
			summary_form: {
				main_details: {
					/**
					 * M​a​i​n​ ​d​e​t​a​i​l​s
					 */
					title: string
					/**
					 * C​a​l​e​n​d​a​r
					 */
					calendar: string
				}
				voting_setup: {
					/**
					 * V​o​t​i​n​g​ ​s​e​t​u​p
					 */
					title: string
					/**
					 * Q​u​e​s​t​i​o​n
					 */
					question: string
					/**
					 * T​y​p​e
					 */
					type: string
					/**
					 * M​a​x​i​m​u​m​ ​-​ ​{​l​i​m​i​t​}​ ​o​p​t​i​o​n​s
					 * @param {number} limit
					 */
					maximum: RequiredParams<'limit'>
					types: {
						/**
						 * S​i​n​g​l​e​ ​c​h​o​i​c​e​ ​-​ ​Y​e​s​ ​/​ ​N​o​ ​/​ ​A​b​s​t​a​i​n
						 */
						SINGLE_CHOICE: string
						/**
						 * S​i​n​g​l​e​ ​c​h​o​i​c​e​ ​-​ ​M​u​l​t​i​p​l​e​ ​v​o​t​i​n​g​ ​o​p​t​i​o​n​s
						 */
						SINGLE_OPTION: string
						/**
						 * M​u​l​t​i​p​l​e​ ​c​h​o​i​c​e​ ​-​ ​M​u​l​t​i​p​l​e​ ​v​o​t​i​n​g​ ​o​p​t​i​o​n​s
						 */
						MULTIPLE_OPTIONS: string
					}
				}
				/**
				 * P​u​b​l​i​s​h​ ​P​r​o​p​o​s​a​l
				 */
				publish_proposal: string
				/**
				 * P​l​e​a​s​e​ ​n​o​t​e​ ​t​h​a​t​ ​o​n​c​e​ ​t​h​e​ ​c​a​m​p​a​i​g​n​ ​i​s​ ​p​u​b​l​i​s​h​e​d​,​ ​i​t​ ​c​a​n​ ​o​n​l​y​ ​b​e​ ​e​d​i​t​e​d​ ​w​h​i​l​e​ ​o​n​ ​"​D​r​a​f​t​"​ ​s​t​a​t​e​,​ ​m​e​a​n​i​n​g​ ​b​e​f​o​r​e​ ​t​h​e​ ​v​o​t​i​n​g​ ​c​a​l​e​n​d​a​r​ ​s​t​a​r​t​s​.
				 */
				publish_description: string
				/**
				 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​p​u​b​l​i​s​h​ ​t​h​i​s​ ​p​r​o​p​o​s​a​l​?
				 */
				publish_sub_description: string
				/**
				 * P​u​b​l​i​s​h​i​n​g​ ​f​a​i​l​e​d
				 */
				publish_failed: string
				/**
				 * T​h​e​ ​p​u​b​l​i​s​h​i​n​g​ ​o​f​ ​t​h​e​ ​p​r​o​p​o​s​a​l​ ​c​o​u​l​d​n​’​t​ ​b​e​ ​c​o​m​p​l​e​t​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
				 */
				publish_failed_description: string
				/**
				 * P​r​o​p​o​s​a​l​ ​p​u​b​l​i​s​h​e​d
				 */
				publish_success: string
				/**
				 * T​h​e​ ​p​r​o​p​o​s​a​l​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​p​u​b​l​i​s​h​ ​a​n​d​ ​c​a​n​ ​n​o​w​ ​b​e​ ​s​e​e​n​ ​p​u​b​l​i​c​l​y​.
				 */
				publish_success_description: string
			}
		}
	}
	proposals: {
		/**
		 * P​r​o​p​o​s​a​l​s
		 */
		title: string
		/**
		 * C​r​e​a​t​e​ ​P​r​o​p​o​s​a​l
		 */
		create: string
		/**
		 * S​e​a​r​c​h​ ​p​r​o​p​o​s​a​l​s​.​.​.
		 */
		search_placeholder: string
		/**
		 * N​o​ ​p​r​o​p​o​s​a​l​s​ ​f​o​u​n​d
		 */
		no_proposals: string
		/**
		 * {​c​u​r​r​e​n​t​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​p​r​o​p​o​s​a​l​s
		 * @param {number} current
		 * @param {number} total
		 */
		pagination: RequiredParams<'current' | 'total'>
	}
	statuses: {
		/**
		 * V​o​t​e​d
		 */
		voted: string
	}
	badge: {
		/**
		 * D​r​a​f​t
		 */
		draft: string
		/**
		 * U​p​c​o​m​i​n​g
		 */
		upcoming: string
		/**
		 * V​o​t​i​n​g​ ​n​o​w
		 */
		voting: string
		/**
		 * A​p​p​r​o​v​e​d
		 */
		approved: string
		/**
		 * E​x​e​c​u​t​e​d
		 */
		executed: string
		/**
		 * C​a​n​c​e​l​e​d
		 */
		canceled: string
		/**
		 * R​e​j​e​c​t​e​d
		 */
		rejected: string
	}
	filters: {
		sort: {
			/**
			 * N​e​w​e​s​t
			 */
			newest: string
			/**
			 * O​l​d​e​s​t
			 */
			oldest: string
			/**
			 * M​o​s​t​ ​p​a​r​t​i​c​i​p​a​n​t
			 */
			most_participant: string
			/**
			 * L​e​a​s​t​ ​p​a​r​t​i​c​i​p​a​n​t
			 */
			least_participant: string
		}
	}
	header: {
		/**
		 * O​f​f​i​c​i​a​l
		 */
		official: string
		/**
		 * V​e​C​h​a​i​n​T​h​o​r​ ​B​l​o​c​k​c​h​a​i​n
		 */
		blockchain: string
		/**
		 * v​o​t​i​n​g​ ​p​l​a​t​f​o​r​m
		 */
		voting_platform: string
		/**
		 * I​m​m​u​t​a​b​l​e​.
		 */
		immutable: string
		/**
		 * T​r​a​n​s​p​a​r​e​n​t​.
		 */
		transparent: string
		/**
		 * D​e​c​e​n​t​r​a​l​i​z​e​d​.
		 */
		decentralized: string
	}
	footer: {
		/**
		 * A​l​l​ ​R​i​g​h​t​s​ ​R​e​s​e​r​v​e​d​ ​©​ ​V​e​c​h​a​i​n​ ​F​o​u​n​d​a​t​i​o​n​ ​S​a​n​ ​M​a​r​i​n​o​ ​S​.​r​.​l​.
		 */
		all_right: string
		legal: {
			/**
			 * T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e
			 */
			terms_of_service: string
			/**
			 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
			 */
			privacy_policy: string
			/**
			 * C​o​o​k​i​e​s​ ​P​o​l​i​c​y
			 */
			cookies_policy: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Homepage
	 */
	homepage: () => LocalizedString
	/**
	 * Back
	 */
	back: () => LocalizedString
	/**
	 * Start
	 */
	start: () => LocalizedString
	/**
	 * End
	 */
	end: () => LocalizedString
	/**
	 * Edit
	 */
	edit: () => LocalizedString
	/**
	 * On
	 */
	on: () => LocalizedString
	/**
	 * All
	 */
	all: () => LocalizedString
	/**
	 * Finished
	 */
	finished: () => LocalizedString
	/**
	 * Show more
	 */
	show_more: () => LocalizedString
	/**
	 * Exit
	 */
	exit: () => LocalizedString
	/**
	 * Next
	 */
	next: () => LocalizedString
	/**
	 * Learn more
	 */
	learn_more: () => LocalizedString
	/**
	 * See details
	 */
	see_details: () => LocalizedString
	/**
	 * Select
	 */
	select: () => LocalizedString
	/**
	 * Select between
	 */
	select_between: () => LocalizedString
	/**
	 * and
	 */
	and: () => LocalizedString
	/**
	 * one
	 */
	one: () => LocalizedString
	/**
	 * Voting
	 */
	voting: () => LocalizedString
	/**
	 * Voters
	 */
	voters: () => LocalizedString
	/**
	 * Most voted
	 */
	most_voted: () => LocalizedString
	/**
	 * Votes
	 */
	votes: () => LocalizedString
	/**
	 * Delete
	 */
	'delete': () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * %
	 */
	percentage: () => LocalizedString
	/**
	 * Submit
	 */
	submit: () => LocalizedString
	/**
	 * Voting Power
	 */
	voting_power: () => LocalizedString
	/**
	 * Voted
	 */
	voted: () => LocalizedString
	/**
	 * Vote
	 */
	vote: () => LocalizedString
	/**
	 * Wallet
	 */
	wallet: () => LocalizedString
	/**
	 * Block #
	 */
	block: () => LocalizedString
	/**
	 * Node
	 */
	node: () => LocalizedString
	/**
	 * Go back
	 */
	go_back: () => LocalizedString
	/**
	 * Optional
	 */
	optional: () => LocalizedString
	/**
	 * Buy a Node
	 */
	buy_a_node: () => LocalizedString
	/**
	 * {current}/{max}
	 */
	filed_length: (arg: { current: number, max: number }) => LocalizedString
	/**
	 * Upload
	 */
	upload: () => LocalizedString
	/**
	 * Image size should be 1280x512px (ratio 3:1).
JPG, PNG or SVG of maximum of {size}MB.
	 */
	file_upload_description: (arg: { size: number }) => LocalizedString
	/**
	 * Select date
	 */
	select_date: () => LocalizedString
	/**
	 * Select time
	 */
	select_time: () => LocalizedString
	/**
	 * Maximum
	 */
	maximum: () => LocalizedString
	/**
	 * Option {index}
	 */
	number_option: (arg: { index: number }) => LocalizedString
	/**
	 * Continue
	 */
	'continue': () => LocalizedString
	/**
	 * Description
	 */
	description: () => LocalizedString
	/**
	 * Preview
	 */
	preview: () => LocalizedString
	/**
	 * Close
	 */
	close: () => LocalizedString
	/**
	 * Confirm
	 */
	confirm: () => LocalizedString
	/**
	 * Try Again
	 */
	try_again: () => LocalizedString
	/**
	 * Read full description
	 */
	read_full_description: () => LocalizedString
	home: {
		/**
		 * Home
		 */
		title: () => LocalizedString
		/**
		 * Go to proposals
		 */
		go_to_proposals: () => LocalizedString
	}
	field_errors: {
		/**
		 * Required
		 */
		required: () => LocalizedString
		/**
		 * Invalid format
		 */
		invalid_format: () => LocalizedString
		/**
		 * The end date must be after the start date
		 */
		end_before_start: () => LocalizedString
		/**
		 * The end date must be in the future
		 */
		end_before_today: () => LocalizedString
	}
	voting_list: {
		/**
		 * Voting options:
		 */
		voting_options: () => LocalizedString
		/**
		 * option to vote:
		 */
		option_to_vote: () => LocalizedString
	}
	proposal: {
		/**
		 * Proposal
		 */
		title: () => LocalizedString
		/**
		 * Proposed by
		 */
		proposed_by: () => LocalizedString
		/**
		 * Voting calendar
		 */
		voting_calendar: () => LocalizedString
		/**
		 * Who can vote
		 */
		who_can_vote: () => LocalizedString
		/**
		 * VeChain Foundation
		 */
		vechain_foundation: () => LocalizedString
		/**
		 * Node holders with voting power will be able to vote on this proposal.
		 */
		node_holders: () => LocalizedString
		/**
		 * Voting will start {date}
		 */
		voting_will_start: (arg: { date: string }) => LocalizedString
		/**
		 * See your vote details
		 */
		see_your_vote: () => LocalizedString
		/**
		 * See all voters
		 */
		see_all_voters: () => LocalizedString
		/**
		 * Mark as executed
		 */
		mark_as_executed: () => LocalizedString
		/**
		 * Buy another node to increase your voting power on future proposals.
		 */
		buy_another_node: () => LocalizedString
		/**
		 * Voting is only possible for Node holders. Buy a node to vote on future proposals or increase your voting power.
		 */
		buy_a_node: () => LocalizedString
		cancel_proposal: {
			/**
			 * Cancel proposal
			 */
			title: () => LocalizedString
			/**
			 * Canceling the proposal means it the voting will not take place and the proposal will not have no results.
			 */
			description: () => LocalizedString
			/**
			 * Reason
			 */
			reason: () => LocalizedString
			/**
			 * Write the reason for cancellation...
			 */
			reason_placeholder: () => LocalizedString
		}
		delete_proposal: {
			/**
			 * Delete proposal
			 */
			title: () => LocalizedString
			/**
			 * If you delete this draft, all the information of the proposal will not be possible to recover anymore.
			 */
			description: () => LocalizedString
			/**
			 * Are you sure you want to delete it?
			 */
			confirmation: () => LocalizedString
			/**
			 * No, go back
			 */
			no_go_back: () => LocalizedString
			/**
			 * Yes, Delete Proposal
			 */
			yes_delete: () => LocalizedString
		}
		info_box: {
			info: {
				/**
				 * Minimum participation
				 */
				title: () => LocalizedString
				/**
				 * A minimum of 30% participation must be reached to validate the voting of the proposal and get approval.
				 */
				description: () => LocalizedString
			}
			approved: {
				/**
				 * Minimum participation reached
				 */
				title: () => LocalizedString
				/**
				 * The voting participation reached the minimum required of 30% to get approval.
				 */
				description: () => LocalizedString
			}
			executed: {
				/**
				 * Proposal Approved and Executed
				 */
				title: () => LocalizedString
				/**
				 * The voting approved the proposal and the actions have been executed.
				 */
				description: () => LocalizedString
			}
			'min-not-reached': {
				/**
				 * Minimum participation not reached
				 */
				title: () => LocalizedString
				/**
				 * The voting participation didn’t reached the minimum required of 30% to get approval.
				 */
				description: () => LocalizedString
			}
			rejected: {
				/**
				 * Proposal Rejected
				 */
				title: () => LocalizedString
				/**
				 * The proposal didn’t get enough votes in favor to get approval.
				 */
				description: () => LocalizedString
			}
			canceled: {
				/**
				 * Proposal Canceled
				 */
				title: () => LocalizedString
				/**
				 * The proposal was canceled by VeChain or the proposer by the following reason:
				 */
				description: () => LocalizedString
			}
		}
		voting_power: {
			/**
			 * Voting Power
			 */
			title: () => LocalizedString
			/**
			 * Your voting power was calculated at the time of the snapshot {snapshot}.
			 */
			calculation: (arg: { snapshot: string }) => LocalizedString
			/**
			 * Total voting power
			 */
			total_voting_power: () => LocalizedString
		}
		voters_table: {
			filters: {
				/**
				 * Search by address...
				 */
				search_by_address: () => LocalizedString
				/**
				 * Voting options
				 */
				voting_options: () => LocalizedString
				/**
				 * Node
				 */
				node: () => LocalizedString
				/**
				 * Sort by
				 */
				sort_by: () => LocalizedString
			}
			header: {
				/**
				 * Date
				 */
				date: () => LocalizedString
				/**
				 * Address
				 */
				address: () => LocalizedString
				/**
				 * Node
				 */
				node: () => LocalizedString
				/**
				 * Node ID
				 */
				node_id: () => LocalizedString
				/**
				 * Voting Power
				 */
				voting_power: () => LocalizedString
				/**
				 * Voted option
				 */
				voted_option: () => LocalizedString
				/**
				 * Transaction ID
				 */
				transaction_id: () => LocalizedString
			}
		}
		create: {
			/**
			 * Previewing proposal
			 */
			previewing: () => LocalizedString
			/**
			 * Create Proposal
			 */
			title: () => LocalizedString
			/**
			 * {current} of {total}
			 */
			steps: (arg: { current: number, total: number }) => LocalizedString
			/**
			 * Add the main details and setup the calendar
			 */
			voting_details_desc: () => LocalizedString
			/**
			 * Define the voting setup details
			 */
			voting_setup_desc: () => LocalizedString
			/**
			 * Review all the details before publishing
			 */
			voting_summary_desc: () => LocalizedString
			/**
			 * Add new option
			 */
			add_new_option: () => LocalizedString
			exit_proposal: {
				/**
				 * Exit proposal creation
				 */
				title: () => LocalizedString
				/**
				 * By exiting you lose all the information written or you can save this proposal as a draft and finish later?
				 */
				description: () => LocalizedString
				/**
				 * You will lose all entered information if you exit now. Saving as a draft is only available on the final step of the form.
				 */
				description_last_step: () => LocalizedString
				/**
				 * Be aware that a draft proposal already exists. Saving now will overwrite your previous draft.
				 */
				description_draft_exist: () => LocalizedString
				/**
				 * Exit proposal
				 */
				exit_button: () => LocalizedString
				/**
				 * Save draft
				 */
				save_button: () => LocalizedString
			}
			draft_saved: {
				/**
				 * Draft saved!
				 */
				title: () => LocalizedString
				/**
				 * The proposal draft has been saved successfully and can now be continued later.
				 */
				description: () => LocalizedString
			}
			details_form: {
				/**
				 * Title
				 */
				title: () => LocalizedString
				/**
				 * What’s the proposal title?
				 */
				title_placeholder: () => LocalizedString
				/**
				 * Description
				 */
				description: () => LocalizedString
				/**
				 * Add a description...
				 */
				description_placeholder: () => LocalizedString
				/**
				 * Header image
				 */
				header_image: () => LocalizedString
				/**
				 * Voting calendar
				 */
				voting_calendar: () => LocalizedString
			}
			setup_form: {
				/**
				 * Voting type
				 */
				voting_type: () => LocalizedString
				/**
				 * Select the type
				 */
				voting_type_subtitle: () => LocalizedString
				/**
				 * Voting Question
				 */
				voting_question: () => LocalizedString
				/**
				 * This question should provide exact context to the voting options:
				 */
				voting_question_subtitle: () => LocalizedString
				/**
				 * Write the question...
				 */
				voting_question_placeholder: () => LocalizedString
				/**
				 * Voting limit
				 */
				voting_limit: () => LocalizedString
				/**
				 * Define the maximum amount of options allowed per voter:
				 */
				voting_limit_subtitle: () => LocalizedString
				/**
				 * Voting options
				 */
				voting_options: () => LocalizedString
				/**
				 * The “single choice” voting type only allows the voter to select:
				 */
				voting_choice_subtitle: () => LocalizedString
				/**
				 * Add between 2 and 30 options to vote:
				 */
				voting_options_subtitle: () => LocalizedString
				/**
				 * Add new option
				 */
				add_new_option: () => LocalizedString
				/**
				 * Write the voting option...
				 */
				voting_option_placeholder: () => LocalizedString
				voting_types: {
					single_choice: {
						/**
						 * Single choice
						 */
						title: () => LocalizedString
						/**
						 * Yes / No / Abstain
						 */
						subtitle: () => LocalizedString
					}
					single_option: {
						/**
						 * Single choice
						 */
						title: () => LocalizedString
						/**
						 * Voter can select 1 of multiple options
						 */
						subtitle: () => LocalizedString
					}
					multi_options: {
						/**
						 * Multiple choice
						 */
						title: () => LocalizedString
						/**
						 * Voter can select 1 or more options
						 */
						subtitle: () => LocalizedString
					}
				}
			}
			summary_form: {
				main_details: {
					/**
					 * Main details
					 */
					title: () => LocalizedString
					/**
					 * Calendar
					 */
					calendar: () => LocalizedString
				}
				voting_setup: {
					/**
					 * Voting setup
					 */
					title: () => LocalizedString
					/**
					 * Question
					 */
					question: () => LocalizedString
					/**
					 * Type
					 */
					type: () => LocalizedString
					/**
					 * Maximum - {limit} options
					 */
					maximum: (arg: { limit: number }) => LocalizedString
					types: {
						/**
						 * Single choice - Yes / No / Abstain
						 */
						SINGLE_CHOICE: () => LocalizedString
						/**
						 * Single choice - Multiple voting options
						 */
						SINGLE_OPTION: () => LocalizedString
						/**
						 * Multiple choice - Multiple voting options
						 */
						MULTIPLE_OPTIONS: () => LocalizedString
					}
				}
				/**
				 * Publish Proposal
				 */
				publish_proposal: () => LocalizedString
				/**
				 * Please note that once the campaign is published, it can only be edited while on "Draft" state, meaning before the voting calendar starts.
				 */
				publish_description: () => LocalizedString
				/**
				 * Are you sure you want to publish this proposal?
				 */
				publish_sub_description: () => LocalizedString
				/**
				 * Publishing failed
				 */
				publish_failed: () => LocalizedString
				/**
				 * The publishing of the proposal couldn’t be completed. Please try again.
				 */
				publish_failed_description: () => LocalizedString
				/**
				 * Proposal published
				 */
				publish_success: () => LocalizedString
				/**
				 * The proposal has been successfully publish and can now be seen publicly.
				 */
				publish_success_description: () => LocalizedString
			}
		}
	}
	proposals: {
		/**
		 * Proposals
		 */
		title: () => LocalizedString
		/**
		 * Create Proposal
		 */
		create: () => LocalizedString
		/**
		 * Search proposals...
		 */
		search_placeholder: () => LocalizedString
		/**
		 * No proposals found
		 */
		no_proposals: () => LocalizedString
		/**
		 * {current} of {total} proposals
		 */
		pagination: (arg: { current: number, total: number }) => LocalizedString
	}
	statuses: {
		/**
		 * Voted
		 */
		voted: () => LocalizedString
	}
	badge: {
		/**
		 * Draft
		 */
		draft: () => LocalizedString
		/**
		 * Upcoming
		 */
		upcoming: () => LocalizedString
		/**
		 * Voting now
		 */
		voting: () => LocalizedString
		/**
		 * Approved
		 */
		approved: () => LocalizedString
		/**
		 * Executed
		 */
		executed: () => LocalizedString
		/**
		 * Canceled
		 */
		canceled: () => LocalizedString
		/**
		 * Rejected
		 */
		rejected: () => LocalizedString
	}
	filters: {
		sort: {
			/**
			 * Newest
			 */
			newest: () => LocalizedString
			/**
			 * Oldest
			 */
			oldest: () => LocalizedString
			/**
			 * Most participant
			 */
			most_participant: () => LocalizedString
			/**
			 * Least participant
			 */
			least_participant: () => LocalizedString
		}
	}
	header: {
		/**
		 * Official
		 */
		official: () => LocalizedString
		/**
		 * VeChainThor Blockchain
		 */
		blockchain: () => LocalizedString
		/**
		 * voting platform
		 */
		voting_platform: () => LocalizedString
		/**
		 * Immutable.
		 */
		immutable: () => LocalizedString
		/**
		 * Transparent.
		 */
		transparent: () => LocalizedString
		/**
		 * Decentralized.
		 */
		decentralized: () => LocalizedString
	}
	footer: {
		/**
		 * All Rights Reserved © Vechain Foundation San Marino S.r.l.
		 */
		all_right: () => LocalizedString
		legal: {
			/**
			 * Terms of Service
			 */
			terms_of_service: () => LocalizedString
			/**
			 * Privacy Policy
			 */
			privacy_policy: () => LocalizedString
			/**
			 * Cookies Policy
			 */
			cookies_policy: () => LocalizedString
		}
	}
}

export type Formatters = {}
