name: Codebase Versioning

on:
  pull_request:
    branches: 
      - fix/vercel-deployment
    # types: [closed]

jobs:
  semantic-versioning:
    uses: vechain/github-actions/.github/workflows/semantic-versioning.yaml@v.1.1.8
    secrets:
      DEPLOY_KEY: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}
    
