name: Contract Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      contracts-changed: ${{ steps.changes.outputs.contracts }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for Changes
        id: changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            contracts:
              - 'packages/contracts/**'

  solidity-coverage:
    name: Run Coverage and Upload
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.contracts-changed == 'true'
    env:
      NODE_OPTIONS: --max-old-space-size=8192

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node v22
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Solidity compilers
        uses: actions/cache@v3
        with:
          path: ~/.cache/hardhat-nodejs
          key: ${{ runner.os }}-solc-${{ hashFiles('./packages/contracts/hardhat.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-solc-

      - name: Run Solidity Coverage Tests
        run: yarn test:coverage:solidity

      - name: Create .nyc_output Directory
        run: mkdir -p packages/contracts/.nyc_output

      - name: Generate Final Coverage Report
        working-directory: packages/contracts
        run: yarn coverage:report

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          directory: packages/contracts/coverage/
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  run-slither:
    name: Slither Analysis
    uses: vechain/github-actions/.github/workflows/slither.yaml@62cc6d6dc08c6a49518766e877942685f080b443 # v.1.9.0
    needs: check-changes
    if: needs.check-changes.outputs.contracts-changed == 'true'
    with:
      target: "packages/contracts/"
      solc-version: "0.8.20"
      fail-on: none
      slither-args: '--filter-paths "(openzeppelin|mocks|interfaces|deprecated|templates|NodeManagement|external)" --exclude-informational --exclude-optimization --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/'
      skip-change-detection: true
    secrets:
      MNEMONIC: ${{ secrets.MNEMONIC }}
      TESTNET_STAGING_MNEMONIC: ${{ secrets.TESTNET_STAGING_MNEMONIC }}
      VECHAIN_URL_DEVNET: ${{ secrets.VECHAIN_URL_DEVNET }}
