# This workflow is triggered when a release is published:
# It will check that the version in the package.json matches the tag name on the last commit
# If version matches it will then deploy the frontend app to the production environment on Vercel
name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GITHUB_RELEASE: "true"
on:
  release:
    types: [published]
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
     
      - name: Get version in package.json
        id: package-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"

      - name: Ensure the package.json version matches the tag version
        if: ${{ steps.package-version.outputs.prop != github.ref_name }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('The version in the package must match the tag.')
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}