name: Plan or Deploy VeVote

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy'
        required: true
        default: dev
        type: string
  workflow_call:
    inputs:
      environment:
        description: Which environment to plan/deploy to
        required: true
        default: dev
        type: string
      version:
        description: The version of this release
        required: false
        type: string
      force:
        description: Whether to force apply
        required: false
        default: false
        type: boolean

# Required for authentication through GitHub OIDC
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  ENVIRONMENT: ${{ inputs.environment || 'dev' }}
  VERCEL_API_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy:
    name: "Plan/deploy VeVote terraform - ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ (inputs.environment == 'prod-preview') && 'prod' || inputs.environment }}

    defaults:
      run:
        working-directory: terraform/vercel

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ACC_ROLE }}

      # Required for Terraform to source modules from other vechain repositories
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.3
          terraform_wrapper: true

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Initialize
        id: init
        run: |
          if [[ "${{ env.ENVIRONMENT }}" == "prod-preview" ]]; then
            terraform init -backend-config="../config/prod/backend.config" -var="preview_mode=true"
          else
            terraform init -backend-config="../config/${{ env.ENVIRONMENT }}/backend.config"
          fi

      - name: Terraform Workspace
        id: workspace
        run: terraform workspace select --or-create  ${{ env.ENVIRONMENT }}

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Update tag
        id: update-tag
        if: inputs.version && inputs.version != 'latest'
        run: |
          ENV_DIR="${{ env.ENVIRONMENT }}"
          if [[ "${{ env.ENVIRONMENT }}" == "prod-preview" ]]; then
            ENV_DIR="prod"
          fi
          sed -i "s/latest/${{ inputs.version }}/g" ../config/${ENV_DIR}/common.yaml
          cat ../config/${ENV_DIR}/common.yaml
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        run: |
          if [[ "${{ env.ENVIRONMENT }}" == "prod-preview" ]]; then
            terraform plan -var="preview_mode=true" -out "apply.plan"
          else
            terraform plan -out "apply.plan"
          fi

      - name: Terraform Apply (PR builds will only plan, never deploy)
        if: github.ref == 'refs/heads/main' || inputs.force
        id: apply
        run: |
          if [[ "${{ env.ENVIRONMENT }}" == "prod-preview" ]]; then
            terraform apply -var="preview_mode=true" "apply.plan"
          else
            terraform apply "apply.plan"
          fi
