name: Unit Test Coverage

on:
  workflow_dispatch:

jobs:
  run-coverage:
    name: Unit tests coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run FE coverage
        id: fe-coverage
        run: yarn test:coverage:fe

      - name: Archive FE coverage
        if: steps.fe-coverage.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: fe-coverage
          path: apps/frontend/coverage
          retention-days: 10
